# Generated by Django 4.2.8 on 2024-01-07 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(default='COMING SOON', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HigherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooseboard', models.CharField(choices=[('ICSE', 'ICSE'), ('CBSE', 'CBSE'), ('State', 'State')], max_length=255)),
                ('startdateyear', models.DateField()),
                ('enddateyear', models.DateField()),
                ('entergrade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooseboard', models.CharField(choices=[('ICSE', 'ICSE'), ('CBSE', 'CBSE'), ('State', 'State')], max_length=255)),
                ('startdateyear', models.DateField()),
                ('enddateyear', models.DateField()),
                ('entergrade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooseboard', models.CharField(choices=[('ICSE', 'ICSE'), ('CBSE', 'CBSE'), ('State', 'State')], max_length=255)),
                ('startdateyear', models.DateField()),
                ('enddateyear', models.DateField()),
                ('Pursuing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.URLField()),
                ('Linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.work')),
                ('WorkDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.workdetails')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.education')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='highereducation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.highereducation'),
        ),
        migrations.AddField(
            model_name='education',
            name='secondaryeducation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.secondaryeducation'),
        ),
    ]
