# Generated by Django 4.1.6 on 2023-02-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userprofile_otp_history'),
        ('blog', '0002_alter_blogmodel_user_alter_chatmodel_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentboxmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentbox_user', to='authentication.userprofile'),
        ),
    ]
