# Generated by Django 4.1.6 on 2023-03-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userprofile_otp_history'),
        ('blog', '0004_likebuttonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebuttonmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='like_user', to='authentication.userprofile'),
        ),
    ]
