# Generated by Django 4.1.6 on 2023-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_likebuttonmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likebuttonmodel',
            old_name='is_shown',
            new_name='is_liked',
        ),
        migrations.AddField(
            model_name='likebuttonmodel',
            name='model_name',
            field=models.CharField(blank=True, choices=[('BG', 'blog'), ('CT', 'Chat')], default='BG', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='likebuttonmodel',
            name='post',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='likebuttonmodel',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
