# Generated by Django 4.1.6 on 2023-03-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_is_shown_likebuttonmodel_is_liked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likebuttonmodel',
            old_name='post',
            new_name='blog_id',
        ),
        migrations.AlterUniqueTogether(
            name='likebuttonmodel',
            unique_together={('model_name', 'user', 'blog_id')},
        ),
    ]
