# Generated by Django 4.1.6 on 2023-03-29 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_rename_post_likebuttonmodel_blog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, choices=[('BG', 'blog'), ('CT', 'Chat')], default='BG', max_length=180, null=True)),
                ('user', models.CharField(max_length=255)),
                ('blog_id', models.CharField(max_length=255)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_attended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Report_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Report_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('model_name', 'user', 'blog_id')},
            },
        ),
    ]
