# Generated by Django 4.1.6 on 2023-02-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userprofile_otp_history'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='univesity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='about_univesity_name', to='education.universitymodel'),
        ),
        migrations.AddField(
            model_name='feedmodel',
            name='univesity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed_univesity_name', to='education.universitymodel'),
        ),
        migrations.AlterField(
            model_name='feedmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed_user', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
