# Generated by Django 4.1.6 on 2023-02-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_aboutmodel_univesity_name_feedmodel_univesity_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='th_cert',
            new_name='tenth_cert',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='twelveth_cert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
