# Generated by Django 4.1.6 on 2023-02-22 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userprofile_otp_history'),
        ('education', '0002_aboutmodel_univesity_name_feedmodel_univesity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='slot_student', to='authentication.userprofile'),
        ),
        migrations.DeleteModel(
            name='CommentBoxModel',
        ),
    ]
