# Generated by Django 4.1.6 on 2023-02-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_slotmodel_student_delete_commentboxmodel'),
        ('education', '0003_rename_th_cert_coursemodel_tenth_cert_and_more'),
    ]

    operations = [
    ]
