# Generated by Django 4.1.6 on 2023-02-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_rename_th_cert_coursemodel_tenth_cert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusmodel',
            name='content_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabusmodel',
            name='topic_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
