# Generated by Django 4.1.6 on 2023-02-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_merge_20230222_1007'),
        ('education', '0004_syllabusmodel_content_count_and_more'),
    ]

    operations = [
    ]
