# Generated by Django 4.1.6 on 2023-02-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_teachcontentmodel_main_catogory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_catogory', models.CharField(blank=True, choices=[('video', 'Video'), ('mcq', 'MCQ'), ('clinical-case', 'Clinical Case'), ('q-bank', 'Q-bank'), ('flash-card', 'Flash card')], default=None, max_length=180, null=True)),
                ('sub_catogory', models.CharField(blank=True, max_length=180, null=True)),
                ('catogory_id', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachcontentmodel',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='teachcontentmodel',
            name='main_catogory',
        ),
        migrations.RemoveField(
            model_name='teachcontentmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='teachcontentmodel',
            name='sub_catogory',
        ),
        migrations.AddField(
            model_name='teachcontentmodel',
            name='catogory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='education.categories'),
        ),
    ]
