# Generated by Django 4.1.6 on 2023-03-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_categories_catogory_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButtonModel',
        ),
    ]
