# Generated by Django 4.1.6 on 2023-03-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_delete_likebuttonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='slug',
            field=models.CharField(blank=True, choices=[('UN', 'university'), ('CS', 'course'), ('BL', 'blog')], max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='user',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
