# Generated by Django 4.1.6 on 2023-03-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_bookmarks_slug_alter_bookmarks_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarks',
            unique_together={('obj_id', 'user', 'slug')},
        ),
    ]
