# Generated by Django 4.1.6 on 2023-03-29 10:57

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_alter_galary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=education.models.get_upload_directory_path),
        ),
    ]
