# Generated by Django 4.1.6 on 2023-04-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_categories_is_premium_syllabusmodel_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymodel',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
