# Generated by Django 4.2.1 on 2023-12-13 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0020_alter_applicationsubmit_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitymodel',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='universitymodel',
            name='univesity_name',
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='university_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='university_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
