# Generated by Django 4.2.8 on 2024-01-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_notification_question_userdata_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='day_of_month',
            field=models.DateField(),
        ),
    ]
