# Generated by Django 4.2.8 on 2024-01-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniversityName', models.CharField(max_length=255)),
                ('UniversityPlace', models.CharField(max_length=255)),
                ('About', models.TextField()),
                ('ranking', models.IntegerField()),
                ('UndergraduatePrograms', models.IntegerField()),
                ('FMGE', models.CharField(max_length=255)),
                ('USML', models.CharField(max_length=255)),
                ('PLAB', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniversityEntrance', models.TextField()),
                ('LectureRooms', models.TextField()),
                ('Laboratory', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.about')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Time', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.about')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('University', models.CharField(max_length=255)),
                ('Place', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
                ('Season', models.CharField(max_length=255)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.about')),
            ],
        ),
    ]
